# feed
title: "Evan Klitzke's web log" 
link: https://eklitzke.org/
description: "Welcome to Evan Klitzke's web log"
author_name: Evan Klitzke
author_email: evan@eklitzke.org
feed_format: rss
# feed item
item_node: td
item_key:
item_vals:
# article link
href_node: a
